# Generated by Django 3.2.6 on 2021-08-19 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='election',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='phrase',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_question', to='multi.question'),
        ),
    ]
