# Generated by Django 3.2.6 on 2021-08-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0002_auto_20210819_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='phrase',
            new_name='option_phrase',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='phrase',
            new_name='question_phrase',
        ),
    ]
