# Generated by Django 3.2.6 on 2021-08-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0003_auto_20210819_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_question', to='multi.question'),
        ),
    ]
