# Generated by Django 3.2.6 on 2021-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0004_auto_20210820_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=60, null=True)),
                ('l_name', models.CharField(blank=True, max_length=60, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='multi')),
                ('website', models.URLField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='candidate',
            field=models.ManyToManyField(blank=True, default='', related_name='option_candidate', to='multi.Candidate'),
        ),
    ]
