# Generated by Django 3.2.6 on 2021-08-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0005_auto_20210820_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('candidate', models.ManyToManyField(blank=True, default='', related_name='response_candidate', to='multi.Candidate')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_phrase',
            new_name='phrase',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_question', to='multi.question'),
        ),
    ]
